### ISSUE TITLE
min() arg is an empty sequence [error]

### ISSUE THREAD

**Issue by JChristopherEllis** [khyox/recentrifuge#29]
Hi,

I tried to run recentrifuge after reinstalling and got the following error. How can I resolve this problem?

Thanks,
Chris

$ rcf -n /nfs/data/bsd/je0/taxdump -k /nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/ -c 2 -o /nfs/data/bsd/je0/schadt/recentrifuge/trimmed/all_quality_trimmed_seqs.html -s KRAKEN -y 25

=-= /nfs/data/bsd/je0/miniconda3/bin/rcf =-= v0.28.14 - December 2019 =-= by Jose Manuel Martí =-=

Kraken .krk files to analyze: ['/nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P1-S1.krk', '/nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P2-S2.krk']
Control(s) sample(s) for subtractions:
        /nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P1-S1.krk
        /nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P2-S2.krk
Loading NCBI nodes... OK!
Loading NCBI names... OK!
Building dict of parent to children taxa... OK!

Please, wait, processing files in parallel...

Loading output file /nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P1-S1.krk... OK!
  Seqs read: 11_788     [5.41 Mnt]
  Seqs clas: 2_197      (81.36% unclassified)
  Seqs pass: 48 (97.82% rejected)
  Scores SHEL: min = 102.0, max = 589.0, avr = 197.6
  Coverage(%): min = 26.3, max = 100.0, avr = 47.8
  Read length: min = 261 nt, max = 783 nt, avr = 364 nt
  TaxIds: by classifier = 529, by filter = 22
Building from raw data with mintaxa = 2 ...
  Check for more seqs lost ([in/ex]clude affects)... OK!
/nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P1-S1 ctrl OK!
Load elapsed time: 0.114 sec

Loading output file /nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P2-S2.krk... OK!
  Seqs read: 11_915     [5.45 Mnt]
  Seqs clas: 2_241      (81.19% unclassified)
  Seqs pass: 52 (97.68% rejected)
  Scores SHEL: min = 97.0, max = 623.0, avr = 232.1
  Coverage(%): min = 25.0, max = 100.0, avr = 57.8
  Read length: min = 266 nt, max = 622 nt, avr = 365 nt
  TaxIds: by classifier = 545, by filter = 20
Building from raw data with mintaxa = 2 ...
  Check for more seqs lost ([in/ex]clude affects)... OK!
/nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P2-S2 ctrl OK!
Load elapsed time: 0.125 sec

Please, wait. Performing cross analysis in parallel...

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/nfs/data/bsd/je0/miniconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/nfs/data/bsd/je0/miniconda3/lib/python3.8/site-packages/recentrifuge/core.py", line 393, in process_rank
    shared_analysis()
  File "/nfs/data/bsd/je0/miniconda3/lib/python3.8/site-packages/recentrifuge/core.py", line 172, in shared_analysis
    min_taxa=get_shared_mintaxa(),
  File "/nfs/data/bsd/je0/miniconda3/lib/python3.8/site-packages/recentrifuge/core.py", line 72, in get_shared_mintaxa
    return min([mintaxas[smpl] for smpl in raws[controls:]])
ValueError: min() arg is an empty sequence
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nfs/data/bsd/je0/miniconda3/bin/rcf", line 813, in <module>
    main()
  File "/nfs/data/bsd/je0/miniconda3/bin/rcf", line 782, in main
    analyze_samples()
  File "/nfs/data/bsd/je0/miniconda3/bin/rcf", line 495, in analyze_samples
    [r.get() for r in async_results]):
  File "/nfs/data/bsd/je0/miniconda3/bin/rcf", line 495, in <listcomp>
    [r.get() for r in async_results]):
  File "/nfs/data/bsd/je0/miniconda3/lib/python3.8/multiprocessing/pool.py", line 768, in get
    raise self._value
ValueError: min() arg is an empty sequence

**Comment by khyox** [comment]
Chris, thanks for the issue report here!

I would say that the problem could be related to a very low number of reads passing the filters (you can see a rejection rate close to 98% in the output) but I don't see any non-control sample beyond the 2 control samples, which does not make sense.

So, please:

1. Update Recentrifuge to the last release since you are using a quite old (beta) version.
2. After the update, if you try again and see the same or a similar problem, please fill the standard form for issues that provides the essential information to look into the problem. I pasted it below for your convenience:




# Bug report

### Bug summary



### Running Recentrifuge

#### Command line



```
$ rcf -n /nfs/data/bsd/je0/taxdump -k /nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/ -c 2 -o /nfs/data/bsd/je0/schadt/recentrifuge/trimmed/all_quality_trimmed_seqs.html -s KRAKEN -y 25
```

#### Data


  * Format of input data?  KRAKEN
  * Control samples (2): 
`/nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P1-S1.krk
/nfs/data/bsd/je0/schadt/kraken2/trimmed/all_krk/P2-S2.krk`
  * Regular samples: __????__

### Actual outcome



```
# If applicable, paste the console output here
#
#
```

### Expected outcome



### Versions 

  * Operating system:
  * Python version:
  * Recentrifuge version: 
  * Release of Kraken (version used to generate the input data):
  * BioPython version:

**Comment by JChristopherEllis** [comment]
Hi Jose,

I installed this two days ago with conda...
conda install -c bioconda recentrifuge

Is there a newer conda install version?

Thanks,
Chris

**Comment by JChristopherEllis** [comment]
Quick update. uninstalled and reinstalled again. I now have new version.

Reran and had no issues. Thanks for your help Jose!

**Comment by khyox** [comment]
Thanks for the update, Chris! I am glad it is working now. Enjoy!
