### ISSUE TITLE
Data from article "Recentrifuge: Robust comparative analysis and contamination removal for metagenomics"

### ISSUE THREAD

**Issue by kla44** [khyox/recentrifuge#33]
Hi ! 
I'm very interested about Recentrifuge, and I would have liked to test on it the data of the article "Recentrifuge: Robust comparative analysis and contamination removal for metagenomics". But, I noticed that these were not present on the GitHub, and that the "http://som1.uv.es/plasmaCFS" link in the article was not functional anymore. 
So, I would like to know if it was possible to have access to these data with an updated link?
I thank you in advance!

**Comment by khyox** [comment]
Hi @kla44. Thanks for the interest in Recentrifuge and in the paper. Thanks also for letting me know that you cannot access the link that appears in the paper. Due to the volume and nature of that data collection, GitHub was not the right place for it. Unfortunately, it's a couple of years since I am not working for the organization originally hosting those data, so I will have to look into this. Maybe the server is just temporally down for maintenance. In me meantime, since this is not directly related to the code (including the documentation) I am closing this issue but, please, also drop an email to the email address for the corresponding author in the paper so that your address can be potentially added to any thread with the relevant sysadmin or IT manager. Thanks!

**Comment by khyox** [comment]
It seems the server suffered several cyberattacks and the sysadmin decided to restrict the access justo to the intranet, which obviously made the link unusable outside the organization. Anyway, the original data for the "plasma CFS" study can be found on the [corresponding ENA repository](https://www.ebi.ac.uk/ena/browser/view/PRJEB14374). If you need more help with this or any other topic related to the paper, please send an email to the address for the corresponding author in the paper. Thanks.
