### ISSUE TITLE
Rextract from Kraken2 output 

### ISSUE THREAD

**Issue by buiguesj** [khyox/recentrifuge#46]
### Question

I tried to run rextract with a kraken2 output but I get the following warning message: No matching read found! Exiting.
Is there a way to extract reads from kraken2 output or it's just made to run with Centrifuge output files??

**Comment by khyox** [comment]
Hi @buiguesj — `Rextract` is oriented to Centrifuge's output. However, it had some support for Kraken output. To test if it supports your version, just try the same command you used but with with `-i 1` (root) instead of `-i 10239`.  If you get some output, then you have support and you just entered a sample without viruses, if you don't, then you haven't support.
