### ISSUE TITLE
what the unassgined means?

### ISSUE THREAD

**Issue by yeli7068** [khyox/recentrifuge#5]
Hi,
Thanks for your works. 
Could you please tell me what the unassigned means? I noticed that the example you used on the github showed the number of count were equal to that of unassigned. Does it stand all the reads classified under that taxid were multiple alignments?

**Comment by khyox** [comment]
After searching for alternative names, I finally decided to keep the name of the different attributes but to add tooltips to them, so that a brief explanation pops up when the mouse is over the attribute in the Recentrifuge web interface. Hopefully, with this, the old terminology is kept, but now the confusion should disappear!
