### ISSUE TITLE
export PDF from recentrifuge results?

### ISSUE THREAD

**Issue by HanZhenZ** [khyox/recentrifuge#6]
It is a great work for us to analyze the metagenome datas. But I have a question shown below. Can I  directly export the PDF for publication from the recentrifuge results? If not available, can you add the function to the recentrifuge? Thank you so much!
The result of centrifuge was analyzed through recentrifuge and pavian. I found that the numbers of raw   reads were different in the recentrifuge and pavian. Of course, the percent of species was also different. Could you found the difference in assessment of recentrifuge? And can you tell me the reason? Thanks.

**Comment by khyox** [comment]
Sorry for the delay in answering.

1. To question 1: you can export the results to PDF through the renewed snapshot function: If you open it, you will get an SVG vectorial image. The easiest way to get a PDF from this file is to open it with a browser and print it as a PDF file. So, you will get a convenient vectorial image in PDF format.

2. To question 2: Recentrifuge directly parses the output of Centrifuge, while in Pavian you can use Centrifuge results by running first `centrifuge-kreport` on Centrifuge output files in order to convert them to kraken report. Maybe this additional step is introducing some differences, but I am not in the Pavian development team so this is just a guess. Could you give me some details (including some quantitative data) of the differences between the output of Recentrifuge and Pavian? Thanks!

**Comment by khyox** [comment]
Closing this as no further data have been provided after months.
